spring:
  profiles:
    active: local
  application:
    name: <App Name>

server:
  port: 8080
  servlet:
    context-path: /api

minio:
  endpoint: <Minio Server> #minio服务地址
  bucket-name: <Bucket Name> #存储桶名称
  access-key: <Access Key> #访问的key
  secret-key: <Secret Key> #访问的密钥
  base-url: <Base URL> #文件预览BaseURL，比如：http://localhost:8080/api/file/preview/

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: <Package Location>
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: <New Name>
